AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

require: rubocop-minitest
