AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

plugins:
  - rubocop-minitest

require:
  - rubocop-rake
