module Logicuit
  module Gates
    # AND gate
    class And < DSL
      attr_reader a: Signals::Signal
      attr_reader b: Signals::Signal
      attr_reader y: Signals::Signal
      class Struct
        attr_reader a: bool
        attr_reader b: bool
      end
      def self.outputs: (*Symbol args, **^(instance) [self: instance] -> bool kwargs) -> void
      def self.assembling: () { () [self: instance] -> void } -> void
    end
  end
end
