module Logicuit
  module Gates
    # NAND gate
    class Nand < DSL
      def self.a: () -> Signals::Signal
      def self.b: () -> Signals::Signal
      def self.y: () -> Signals::Signal

      def a: () -> Signals::Signal
      def b: () -> Signals::Signal
      def y: () -> Signals::Signal
    end
  end
end
