module Logicuit
  module Gates
    # NOT gate
    class Not < DSL
      attr_reader a: Signals::Signal
      attr_reader y: Signals::Signal
      class Struct
        attr_reader a: bool
      end
      def self.outputs: (*Symbol args, **^() [self: Struct] -> bool kwargs) -> void
      def self.assembling: () { () [self: instance] -> void } -> void
    end
  end
end
