module Logicuit
  module Gates
    # OR gate
    class Or < DSL
      def a: () -> Signals::Signal
      def b: () -> Signals::Signal
      def y: () -> Signals::Signal
      class Struct
        attr_reader a: bool
        attr_reader b: bool
      end
      def self.outputs: (*Symbol args, **^() [self: Struct] -> bool kwargs) -> (nil | untyped)
      def self.assembling: () { () [self: instance] -> void } -> void
    end
  end
end
