module Logicuit
  module Circuits
    module Combinational
      # FullAdder class
      class FullAdder < DSL
        attr_reader cin: Signals::Signal
        attr_reader a: Signals::Signal
        attr_reader b: Signals::Signal
        attr_reader s: Signals::Signal
        attr_reader c: Signals::Signal
      end
    end
  end
end
