module Logicuit
  module Circuits
    module Combinational
      # FullAdder class
      class FullAdder < DSL
        def cin: () -> Signals::Signal
        def a: () -> Signals::Signal
        def b: () -> Signals::Signal
        def s: () -> Signals::Signal
        def c: () -> Signals::Signal
        class Struct
          attr_reader cin: bool
          attr_reader a: bool
          attr_reader b: bool
        end
        def self.outputs: (*Symbol args, **^() [self: Struct] -> bool kwargs) -> (nil | untyped)
        def self.assembling: () { () [self: instance] -> void } -> void
      end
    end
  end
end
