module Logicuit
  module Circuits
    module Td4
      # TD4 CPU
      class Cpu < DSL
        @a: untyped

        @b: untyped

        def to_s: () -> ::String

        def in0: () -> Signals::Signal
        def in1: () -> Signals::Signal
        def in2: () -> Signals::Signal
        def in3: () -> Signals::Signal
        def led1: () -> Signals::Signal
        def led2: () -> Signals::Signal
        def led3: () -> Signals::Signal
        def led4: () -> Signals::Signal
        class Struct
          attr_reader in0: bool
          attr_reader in1: bool
          attr_reader in2: bool
          attr_reader in3: bool
        end
        def self.outputs: (*Symbol args, **^() [self: Struct] -> bool kwargs) -> void
        def self.assembling: () { () [self: instance] -> void } -> void
      end
    end
  end
end
