module Logicuit
  module Circuits
    module Td4
      # TD4 CPU
      class Cpu < DSL
        @a: untyped

        @b: untyped

        def to_s: () -> ::String

        attr_reader in0: Signals::Signal
        attr_reader in1: Signals::Signal
        attr_reader in2: Signals::Signal
        attr_reader in3: Signals::Signal
        attr_reader led1: Signals::Signal
        attr_reader led2: Signals::Signal
        attr_reader led3: Signals::Signal
        attr_reader led4: Signals::Signal
      end
    end
  end
end
