module Logicuit
  module Circuits
    module Td4
      # Timer
      class Rom < DSL
        def evaluate: () -> (nil | untyped)

        def self.a3: () -> Signals::Signal
        def self.a2: () -> Signals::Signal
        def self.a1: () -> Signals::Signal
        def self.a0: () -> Signals::Signal
        def self.d7: () -> Signals::Signal
        def self.d6: () -> Signals::Signal
        def self.d5: () -> Signals::Signal
        def self.d4: () -> Signals::Signal
        def self.d3: () -> Signals::Signal
        def self.d2: () -> Signals::Signal
        def self.d1: () -> Signals::Signal
        def self.d0: () -> Signals::Signal

        def a3: () -> Signals::Signal
        def a2: () -> Signals::Signal
        def a1: () -> Signals::Signal
        def a0: () -> Signals::Signal
        def d7: () -> Signals::Signal
        def d6: () -> Signals::Signal
        def d5: () -> Signals::Signal
        def d4: () -> Signals::Signal
        def d3: () -> Signals::Signal
        def d2: () -> Signals::Signal
        def d1: () -> Signals::Signal
        def d0: () -> Signals::Signal
      end
    end
  end
end
