module Logicuit
  module Signals
    # Clock
    class Clock
      self.@instance: Clock

      @downstreams: Array[DSL]

      @tick_count: Integer

      def initialize: () -> void

      attr_reader downstreams: Array[DSL]

      attr_reader tick_count: Integer

      def tick: () -> void

      def self.instance: () -> Clock

      def self.connects_to: (DSL component) -> void

      alias self.>> self.connects_to

      def self.tick: () -> void

      def self.tick_count: () -> Integer
    end
  end
end
