module Logicuit
  module Circuits
    module Sequential
      # D Flip-Flop
      class DFlipFlop < DSL
        def d: () -> Signals::Signal
        def q: () -> Signals::Signal
        class Struct
          attr_reader d: bool
        end
        def self.outputs: (*Symbol args, **^() [self: Struct] -> bool kwargs) -> void
        def self.assembling: () { () [self: instance] -> void } -> void
      end
    end
  end
end
