module Logicuit
  module Circuits
    module Sequential
      # D Flip-Flop
      class DFlipFlop < DSL
        def self.d: () -> Signals::Signal
        def self.q: () -> Signals::Signal

        def d: () -> Signals::Signal
        def q: () -> Signals::Signal
      end
    end
  end
end
