module Logicuit
  module Circuits
    module Sequential
      # 1 bit CPU with a Multiplexer
      # Input A is H, MOV A,A
      # Input A is L, NOT A
      class OneBitCpu < DSL
        attr_reader a: Signals::Signal
        attr_reader y: Signals::Signal
      end
    end
  end
end
