module Logicuit
  module Circuits
    module Sequential
      # 1 bit CPU with a Multiplexer
      # Input A is H, MOV A,A
      # Input A is L, NOT A
      class OneBitCpu < DSL
        def a: () -> Signals::Signal
        def y: () -> Signals::Signal
        class Struct
          attr_reader a: bool
        end
        def self.outputs: (*Symbol args, **^() [self: Struct] -> bool kwargs) -> void
        def self.assembling: () { () [self: instance] -> void } -> void
      end
    end
  end
end
