module Logicuit
  module Circuits
    module Sequential
      # Program Counter
      class ProgramCounter < DSL
        def self.a: () -> Signals::Signal
        def self.b: () -> Signals::Signal
        def self.c: () -> Signals::Signal
        def self.d: () -> Signals::Signal
        def self.ld: () -> Signals::Signal
        def self.qa: () -> Signals::Signal
        def self.qb: () -> Signals::Signal
        def self.qc: () -> Signals::Signal
        def self.qd: () -> Signals::Signal

        def a: () -> Signals::Signal
        def b: () -> Signals::Signal
        def c: () -> Signals::Signal
        def d: () -> Signals::Signal
        def ld: () -> Signals::Signal
        def qa: () -> Signals::Signal
        def qb: () -> Signals::Signal
        def qc: () -> Signals::Signal
        def qd: () -> Signals::Signal
      end
    end
  end
end
